development:
  adapter: postgresql
  encoding: unicode
  database: ubam
  pool: 5
  username: ubam
  password: ub4m
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: ubam
  pool: 5
  username: ubam
  password: ub4m
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: ubam
  pool: 5
  username: ubam
  password: ub4m
  host: localhost
  port: 5432

