source 'http://rubygems.org'

# Current stable rails version
gem 'rails', '3.0.4'

# Postgres backend adapter
gem 'pg'

# JSON parsing
gem 'json'

# Bulk inserts gem
gem 'activerecord-import'

group :development do
  
  # Thin web server
  gem 'thin'

  # Ruby 1.8 debug  
  gem 'ruby-debug'
  
  # Ruby 1.9 debug  
  #gem 'ruby-debug19'
end

